
project:
  type: website

website:
  title: "Mein Wiki"
  description: "Wiki für DVS"

  navbar:
    title: "Mein Wiki"
    left:
      - href: index.qmd
        text: Start

  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Tutorials"
        contents:
          - tutorials\tutorial-1.qmd
          - tutorials\tutorial-2.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    include-after-body:
      - dbml-visualizer.html
    toc: true
    number-sections: false
    code-copy: true
    smooth-scroll: true

execute:
  freeze: auto
