---
title: "Übung 3"
---

# Übung 3 Normalisierung

## Erlauterung


- Überführen Sie den Sachverhalt schrittweise in die 3. Normalform!
- Die Ergebnisse der zweiten und dritten Normalform sind in Relationen-Schreibweise darzustellen.

| Matr.-Nr. | Name          | Geb. Datum | Modul kürzel | Modul Name | Test_ID | Test-Name             | Note          |
| --------- | ------------- | ---------- | ------------ | ---------- | ------- | --------------------- | ------------- |
| 9559789   | Klein, Olaf   | 11.11.73   | V            | VWL        | 1, 4    | BWL-A, VWL-B          | 2,3; 4,0      |
| 9758231   | Schulz, Kevin | 13.02.77   | V            | VWL        | 3       | VWL-A                 | 5,0           |
| 9664978   | Bauer, Tino   | 05.03.76   | B            | BWL        | 1, 3, 5 | BWL-A, VWL-A, Jura PR | 3,3; 5,0; 1,7 |
| 9123875   | Werner Meier  | 19.07.77   | W            | WIING      | 2, 6    | BWL-B, Jura ÖR        | 1,0; 2,0      |


## Lösung 

Meine Lösung:

### 1 NF

| Matr.-Nr. | Name          | Geb. Datum | Modul kürzel | Modul Name | Test_ID | Test-Name             | Note          |
| --------- | ------------- | ---------- | ------------ | ---------- | ------- | --------------------- | ------------- |
| 9559789   | Klein, Olaf   | 11.11.73   | V            | VWL        | 4       |  VWL-B                |  4,0          |
| 9559789   | Klein, Olaf   | 11.11.73   | V            | VWL        | 1       | BWL-A                 | 2,3           |
| 9758231   | Schulz, Kevin | 13.02.77   | V            | VWL        | 3       | VWL-A                 | 5,0           |
| 9664978   | Bauer, Tino   | 05.03.76   | B            | BWL        | 1,      | BWL-A                 | 3,3           |
| 9664978   | Bauer, Tino   | 05.03.76   | B            | BWL        |  3      |        VWL-A,         |      5,0      |
| 9664978   | Bauer, Tino   | 05.03.76   | B            | BWL        |       5 |               Jura PR |           1,7 |
| 9123875   | Werner Meier  | 19.07.77   | W            | WIING      | 2       | BWL-B                 | 1,0           |
| 9123875   | Werner Meier  | 19.07.77   | W            | WIING      |    6    |        Jura ÖR        |      2,0      |


### 2 NF 

| Matr.-Nr. | Name          | Geb. Datum |
| --------- | ------------- | ---------- |
| 9559789   | Klein, Olaf   | 11.11.73   |
| 9758231   | Schulz, Kevin | 13.02.77   |
| 9664978   | Bauer, Tino   | 05.03.76   | 
| 9123875   | Werner Meier  | 19.07.77   |

| Modul kürzel | Modul Name | Test_ID | Test-Name             | Note          | Matr.-Nr. |
| ------------ | ---------- | ------- | --------------------- | ------------- |-----------|
| V            | VWL        | 4       |  VWL-B                |  4,0          |  9559789  |
| V            | VWL        | 1       | BWL-A                 | 2,3           | 9559789   |
| V            | VWL        | 3       | VWL-A                 | 5,0           | 9758231   |
| B            | BWL        | 1,      | BWL-A                 | 3,3           | 9664978   |
| B            | BWL        |  3      |        VWL-A,         |      5,0      | 9664978   |
| B            | BWL        |       5 |               Jura PR |           1,7 | 9664978   |
| W            | WIING      | 2       | BWL-B                 | 1,0           | 9123875   |
| W            | WIING      |    6    |        Jura ÖR        |      2,0      | 9123875   |

### 3 NF

## Erklärung


## Ergebnis von professor 
konnte nicht fotografiert werden :( 

